apiVersion: v1
kind: Service
metadata:
  annotations:
    author: test
    product: test
    version: test
  
  labels:
    test: orderer
  name: orderer
spec:
  type: ClusterIP 
  ports:
  - name: "7050"
    port: 7050
    targetPort: 7050
  selector:
    test: orderer

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    author: test
    product: test
    version: test
  labels:
    test: orderer
  name: orderer
spec:
  serviceName: orderer
  replicas: 1
  selector:
    matchLabels:
      test: orderer
  template:
    metadata:
      labels:
        test: orderer
    spec:
      containers:
      - args:
        - orderer
        env:
        - name: ORDERER_GENERAL_LOGLEVEL
          value: WARNING
        - name: FABRIC_LOGGING_SPEC
          value: WARNING
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /var/hyperledger/orderer/genesis.block
        - name: ORDERER_GENERAL_LOCALMSPID
          value: OrdererMSP
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /var/hyperledger/orderer/msp
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /var/hyperledger/orderer/tls/server.key
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /var/hyperledger/orderer/tls/server.crt
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: /var/hyperledger/orderer/tls/ca.crt
        - name: ORDERER_KAFKA_VERBOSE
          value: "true"
        - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
          value: /var/hyperledger/orderer/tls/server.crt
        - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
          value: /var/hyperledger/orderer/tls/server.key
        - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
          value: /var/hyperledger/orderer/tls/ca.crt
        - name: ORDERER_METRICS_PROVIDER
          value: prometheus
        - name: ORDERER_OPERATIONS_LISTENADDRESS
          value: 0.0.0.0:8443
        - name: ORDERER_GENERAL_LISTENPORT
          value: "7050"
        image: hyperledger/fabric-orderer:2.1
        name: orderer
        ports:
        - containerPort: 7050
        - containerPort: 8443
        volumeMounts:
        - mountPath: /var/hyperledger/orderer/
          name: genesis
        - mountPath: /var/hyperledger/orderer/msp/cacerts/
          name: orderercacerts
        - mountPath: /var/hyperledger/orderer/msp/keystore/
          name: ordererkeystore
        - mountPath: /var/hyperledger/orderer/msp/signcerts/
          name: orderersigncerts
        - mountPath: /var/hyperledger/orderer/msp/
          name: orderermsp
        - mountPath: /var/hyperledger/orderer/tls/
          name: orderertls
        - mountPath: /var/hyperledger/production/orderer
          name: orderer-claim1  
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
      restartPolicy: Always
      volumes:
      - name: genesis
        secret:
          secretName: genesis.block
          items:
          - key: genesis.block
            path: genesis.block
      - name: orderercacerts
        secret:
          secretName: orderer.example.com.msp.cacerts
          items:
          - key: ca.example.com-cert.pem
            path: ca.example.com-cert.pem
      - name: ordererkeystore
        secret:
          secretName: orderer.example.com.msp.keystore
          items:
          - key: priv_sk
            path: priv_sk
      - name: orderersigncerts
        secret:
          secretName: orderer.example.com.msp.signcerts
          items:
          - key: orderer.example.com-cert.pem
            path: orderer.example.com-cert.pem
      - name: orderermsp
        secret:
          secretName: orderer.example.com.msp
          items:
          - key: config.yaml
            path: config.yaml
      - name: orderertls
        secret:
          secretName: orderer.example.com.tls
          items:
          - key: ca.crt
            path: ca.crt
          - key: server.crt
            path: server.crt
          - key: server.key
            path: server.key
      - name: orderer-claim1
        persistentVolumeClaim:
          claimName: orderer-disk-claim
