apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-claim
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 1Gi
---        
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orderer-disk-claim
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 1Gi
---        
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: peer-disk-claim
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 1Gi
